quoman/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('quoman.urls', namespace='quoman')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^cotizaciones/', include('quotes.urls', namespace='quotes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quoman/quoman/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
]

quoman/quotes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^lista/$', views.quotes_list, name='list'),
    url(r'^nuevo/$', views.quotes_new, name='new'),
    url(r'^editar/(?P<codigo>[-_\w]+)/$', views.quotes_edit, name='edit'),
    url(r'^detalle/(?P<codigo>[-_\w]+)/$', views.quotes_detail, name='detail'),
    url(r'^pdf/(?P<codigo>[-_\w]+)/$', views.quotes_pdf, name='pdf'),
    url(r'^enviar/(?P<codigo>[-_\w]+)/$', views.send_quote, name='send_quote'),
]

quoman/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login'),
    url(r'^salir/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.profile, name='profile'),
    url(r'^perfil/password/$', views.update_password, name='update_password'),
    url(r'^olvido-password/$', views.forget_password, name='forget_password'),
    url(r'^cambiar-password/(?P<profile_id>\d+)/(?P<uuid>[^/]+)/$', views.set_password, name='set_password'),
]

quoman/quotes/models.py
from django.core.urlresolvers import reverse
from django.db import models

from . import constants
from products.models import Product
from users.models import User
from quoman.models import Config


class Quote(models.Model):
    fecha_de_creacion = models.DateTimeField('Fecha de creación', auto_now_add=True)
    propietario_id = models.ForeignKey(User, verbose_name='Propietario', blank=True, null=True,
                                       on_delete=models.PROTECT)
    aplica_detraccion = models.BooleanField('Aplica Detracción', default=False)

    estado = models.CharField('Estado', max_length=24, choices=constants.COTIZACION_ESTADO,
                              default=constants.COTIZACION_PENDIENTE, blank=True)
    codigo = models.CharField('Código', max_length=12, unique=True)

    ruc = models.CharField('RUC', max_length=12, blank=True)
    empresa_razon_social = models.CharField('Razón Social', max_length=180)
    empresa_direccion = models.CharField('Dirección', max_length=180)
    representante = models.CharField('Representante', max_length=96, blank=True)
    empresa_telefono = models.CharField('Teléfono de la empresa', max_length=32, blank=True)

    tiempo_de_entrega = models.CharField('Tiempo de Entrega', max_length=96, blank=True)
    valida_hasta = models.CharField('Válida hasta', max_length=120, blank=True, default=None, null=True)
    forma_de_pago = models.CharField('Forma de pago', max_length=180, blank=True)
    costo_de_envio = models.DecimalField('Costo de envío', max_digits=6, decimal_places=2, default=0)
    total = models.DecimalField('Total', max_digits=9, decimal_places=2, default=0)

    igv = models.DecimalField('IGV', max_digits=3, decimal_places=1)

    class Meta:
        verbose_name = 'Cotización'
        verbose_name_plural = 'Cotizaciones'
        ordering = ['fecha_de_creacion']

    def __str__(self):
        return self.codigo

    def save(self, *args, **kwargs):
        self.total = self.calcula_total()
        if not self.igv:
            config, created = Config.objects.get_or_create(pk=1)
            self.igv = config.igv

        super(Quote, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('quotes:edit', kwargs={'codigo': self.codigo})

    def get_detail_url(self):
        return reverse('quotes:detail', kwargs={'codigo': self.codigo})

    def get_pdf_url(self):
        return reverse('quotes:pdf', kwargs={'codigo': self.codigo})

    def get_send_url(self):
        return reverse('quotes:send_quote', kwargs={'codigo': self.codigo})

    def calcula_subtotal_productos(self):
        subtotal = 0
        for producto in self.productos_a_cotizar.all():
            subtotal = subtotal + producto.cantidad * producto.precio

        return subtotal

    def calcula_igv(self):
        subtotal = self.calcula_subtotal_productos()

        total_antes_igv = subtotal + self.costo_de_envio
        return total_antes_igv * self.igv / 100

    def calcula_total(self):
        ''' Incluye el costo de los productos, costo de envío e IGV '''

        subtotal = self.calcula_subtotal_productos()

        total_antes_igv = subtotal + self.costo_de_envio
        total = total_antes_igv + self.calcula_igv()

        return total


class QuoteReceiver(models.Model):
    quote = models.ForeignKey(Quote, verbose_name='', on_delete=models.CASCADE)
    nombres = models.CharField('Nombres', max_length=64, blank=True)
    email = models.EmailField('Email')

    class Meta:
        verbose_name = 'Destinatario de la cotización'
        verbose_name_plural = 'Destinatarios de la cotización'

    def __str__(self):
        return self.email

    def full_email(self):
        if self.nombres:
            return '{}<{}>'.format(self.nombres, self.email)

        return self.email


class QuoteProduct(models.Model):
    quote = models.ForeignKey(Quote, verbose_name='Cotización', related_name='productos_a_cotizar')
    producto = models.ForeignKey(Product, verbose_name='Producto', blank=True, null=True)
    sku = models.CharField('SKU', max_length=32, help_text='Identificador único')
    nombre = models.CharField('Nombre', max_length=64)
    detalle = models.TextField('Detalle', blank=True)
    precio = models.DecimalField('Precio', max_digits=12, decimal_places=2,
                                 help_text='Precio en soles con dos decimales como máximo.')
    cantidad = models.IntegerField('Cantidad', default=1)
    subtotal = models.DecimalField('Subtotal', max_digits=9, decimal_places=2, default=0)

    class Meta:
        verbose_name = 'Producto a cotizar'
        verbose_name_plural = 'Productos a cotizar'
        unique_together = ('quote', 'sku')

    def __str__(self):
        return self.sku

    def save(self, *args, **kwargs):
        self.subtotal = self.calcula_subtotal()
        super(QuoteProduct, self).save(*args, **kwargs)

    def calcula_subtotal(self):
        return self.precio * self.cantidad

quoman/quotes/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Quote, QuoteReceiver, QuoteProduct
from quoman.helpers import DefaultFormHelper


class QuoteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(QuoteForm, self).__init__(*args, **kwargs)
        self.helper = DefaultFormHelper

    class Meta:
        model = Quote
        fields = ('aplica_detraccion', 'ruc', 'empresa_razon_social', 'empresa_direccion', 'empresa_telefono',
                  'representante', 'tiempo_de_entrega', 'valida_hasta', 'forma_de_pago', 'costo_de_envio')


QuoteReceiverFormSet = inlineformset_factory(Quote, QuoteReceiver, extra=0, can_delete=True,
                                             fields=('nombres', 'email'))

class QuoteProductForm(forms.ModelForm):
    class Meta:
        model = QuoteProduct
        fields = ('producto', 'sku', 'nombre', 'detalle', 'precio', 'cantidad')

    def __init__(self, *args, **kwargs):
        super(QuoteProductForm, self).__init__(*args, **kwargs)
        self.fields['producto'].widget.attrs.update({'class': 'producto'})
        self.fields['sku'].widget.attrs.update({'class': 'sku'})
        self.fields['nombre'].widget.attrs.update({'class': 'nombre'})
        self.fields['detalle'].widget.attrs.update({'class': 'detalle'})
        self.fields['precio'].widget.attrs.update({'class': 'precio'})

        self.helper = DefaultFormHelper

QuoteProductFormSet = inlineformset_factory(Quote, QuoteProduct, form=QuoteProductForm, extra=0, can_delete=True)

quoman/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .constants import COTIZACION_PENDIENTE
from .models import Quote
from .forms import QuoteForm, QuoteReceiverFormSet, QuoteProductFormSet
from .pdf import draw_pdf
from .pdf import envia_cotizacion
from .utils import pdf_response
from quoman.models import Config
from quoman.helpers import DefaultFormHelper
from users.constants import ROL_VENDEDOR, ROL_ADMINISTRADOR
from correlativos.utils import genera_codigo
from correlativos.models import CORRELATIVO_COTIZACION


@login_required
def quotes_list(request):
    user = request.user

    if user.userprofile.rol == ROL_VENDEDOR:
        lista_cotizaciones = Quote.objects.filter(propietario_id=user
                                                  ).order_by('-fecha_de_creacion', '-codigo').select_related(
            'propietario_id__userprofile')
    elif user.userprofile.rol == ROL_ADMINISTRADOR or user.is_staff():
        lista_cotizaciones = Quote.objects.order_by('-fecha_de_creacion', '-codigo').select_related(
            'propietario_id__userprofile')

    return render(request, 'quotes/list.html', locals())


@login_required
def quotes_new(request):
    usuario = request.user
    cotizacion = Quote()
    config, created = Config.objects.get_or_create(pk=1)

    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES, instance=cotizacion)
        quoteReceiverFormSet = QuoteReceiverFormSet(request.POST, instance=cotizacion)
        quoteProductFormSet = QuoteProductFormSet(request.POST, instance=cotizacion)

        if form.is_valid() and quoteReceiverFormSet.is_valid() and quoteProductFormSet.is_valid():
            cotizacion = form.save(commit=False)
            cotizacion.propietario_id = usuario
            cotizacion.codigo = genera_codigo(CORRELATIVO_COTIZACION)
            cotizacion.igv = config.igv
            cotizacion.save()

            quoteReceiverFormSet.save()
            quoteProductFormSet.save()

            cotizacion.total = cotizacion.calcula_total()
            cotizacion.save()

            messages.add_message(request, messages.SUCCESS, 'Se registró la cotización')

            return redirect(cotizacion.get_absolute_url())
    else:
        form = QuoteForm()
        quoteReceiverFormSet = QuoteReceiverFormSet(instance=cotizacion)
        quoteProductFormSet = QuoteProductFormSet(instance=cotizacion)

    helper = DefaultFormHelper

    return render(request, 'quotes/new_edit.html', locals())


@login_required
def quotes_edit(request, codigo):
    usuario = request.user
    config, created = Config.objects.get_or_create(pk=1)

    try:
        cotizacion = Quote.objects.get(codigo=codigo)
    except Quote.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No existe la cotización buscada')
        return redirect('quotes:list')

    if cotizacion.propietario_id != usuario and cotizacion.propietario_id.is_superuser:
        messages.add_message(request, messages.WARNING, 'No cuenta con permisos para ver la cotización')
        return redirect('quotes:list')

    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES, instance=cotizacion)
        quoteReceiverFormSet = QuoteReceiverFormSet(request.POST, instance=cotizacion)
        quoteProductFormSet = QuoteProductFormSet(request.POST, instance=cotizacion)

        if form.is_valid() and quoteReceiverFormSet.is_valid() and quoteProductFormSet.is_valid():
            cotizacion = form.save(commit=False)
            cotizacion.igv = config.igv
            cotizacion.save()

            quoteReceiverFormSet.save()
            quoteProductFormSet.save()

            cotizacion.total = cotizacion.calcula_total()
            cotizacion.save()

            for form in quoteProductFormSet:
                form.save()

            messages.add_message(request, messages.SUCCESS, 'Se actualizó la cotización')
            return redirect(cotizacion.get_absolute_url())

    else:
        form = QuoteForm(instance=cotizacion)
        quoteReceiverFormSet = QuoteReceiverFormSet(instance=cotizacion)
        quoteProductFormSet = QuoteProductFormSet(instance=cotizacion)

    helper = DefaultFormHelper

    return render(request, 'quotes/new_edit.html', locals())


@login_required
def quotes_detail(request, codigo):
    try:
        cotizacion = Quote.objects.get(codigo=codigo)
    except Quote.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No existe la cotización buscada')
        return redirect('quotes:list')

    fields = ('fecha_de_creacion', 'propietario_id', 'estado', 'codigo', 'ruc')

    return render(request, 'quotes/detail.html', locals())


@login_required
def quotes_pdf(request, codigo):
    try:
        cotizacion = Quote.objects.get(codigo=codigo)
    except Quote.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No existe la cotización buscada')
        return redirect('quotes:list')

    return pdf_response(draw_pdf, 'cotizacion.pdf', cotizacion)


@login_required
def send_quote(request, codigo):
    data = {'status_code': 200}
    usuario = request.user

    try:
        cotizacion = Quote.objects.get(codigo=codigo)
    except Quote.DoesNotExist:
        data['mensaje'] = 'No existe la cotización buscada'
        data['str_status'] = 'error'
        return JsonResponse(data, status_code=404)

    # validación del usuario
    if cotizacion.propietario_id != usuario and cotizacion.propietario_id.is_superuser:
        data['mensaje'] = 'No cuenta con permisos para enviar esta cotización'
        data['str_status'] = 'error'
        return JsonResponse(data, status_code=403)

    # validación del estado de envío
    if cotizacion.estado != COTIZACION_PENDIENTE:
        data['status_code'] = 409
        data['str_status'] = 'info'
        data['mensaje'] = 'La cotización ya ha sido enviada'
    else:
        respuesta = envia_cotizacion(cotizacion)
        data['status_code'] = respuesta['status_code']
        data['mensaje'] = respuesta['mensaje']

    jsonResponse = JsonResponse(data)
    jsonResponse.status_code = data['status_code']

    return jsonResponse

quoman/templates/quotes/detail.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li><a href='{% url "quotes:list" %}'>Cotizaciones</a></li>
            <li class='active'><a>{{ cotizacion.codigo }}: detalle</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="box">
        <div class="box-body">
          <a class='btn btn-primary btn-send-mail' target='_blank'>
            <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
            Enviar cotización
          </a>

          <a href='{{ cotizacion.get_pdf_url }}' class='btn btn-info' target='_blank'>
            <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
            Ver PDF
          </a>
        </div>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="box">
        <div class="box-header with-border">
          <h1 class='box-title'>Cotización #{{ codigo }}</h1>

          <div class='box-tools'>

          </div>
        </div>

        <div class="box-body">

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Fecha de creación:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.fecha_de_creacion }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Propietario (vendedor):</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.propietario_id }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Tiempo de entrega:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.tiempo_de_entrega }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Válida hasta:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.valida_hasta }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Forma de Pago:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.forma_de_pago }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Costo de envío:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.costo_de_envio }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h2 class='box-title'>Información del cliente</h2>
        </div>

        <div class="box-body">
          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>RUC:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.ruc }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Razón Social:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.empresa_razon_social }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Representante:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.representante }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Dirección:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.empresa_direccion }}
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6 col-lg-4">
              <strong>Teléfono:</strong>
            </div>
            <div class="col-sm-6 col-lg-8">
              {{ cotizacion.empresa_telefono }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="box box-primary">
    <div class="box-header">
      <h2 class="box-title">Productos</h2>
    </div>

    <div class='box-body table-responsive no-padding'>

      <table class='table table-bordered table-responsive table-striped table-hover'>
        <thead>
        <tr>
          <th>#</th>
          <th>SKU</th>
          <th>Nombre</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Subtotal</th>
        </tr>
        </thead>

        <tbody>
        {% for producto in cotizacion.productos_a_cotizar.all %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href='{{ producto.producto.get_absolute_url }}'>{{ producto.sku|upper }}</a></td>
            <td>{{ producto.nombre }}</td>
            <td>S/ {{ producto.precio }}</td>
            <td>{{ producto.cantidad }}</td>
            <td>S/ {{ producto.subtotal }}</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td colspan='4'>{{ producto.detalle }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan='3'>No hay productos registrados</td>
          </tr>
        {% endfor %}

        <tr>
          <td colspan='4'></td>
          <td><strong>Subtotal:</strong></td>
          <td>S/ {{ cotizacion.calcula_subtotal_productos }}</td>
        </tr>

        <tr>
          <td colspan='4'></td>
          <td><strong>Costo de envío:</strong></td>
          <td>S/ {{ cotizacion.costo_de_envio }}</td>
        </tr>

        <tr>
          <td colspan='4'></td>
          <td><strong>IGV:</strong></td>
          <td>{{ cotizacion.igv }} %</td>
        </tr>

        <tr>
          <td colspan='4'></td>
          <td><strong>Total:</strong></td>
          <td>S/ {{ cotizacion.total }}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="box">
        <div class="box-header with-border">
          <h2 class='box-title'>Destinatarios</h2>
        </div>

        <div class="box-body">
          <table class='table table-bordered table-responsive table-striped table-hover'>
            <thead>
            <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Correo</th>
            </tr>
            </thead>

            <tbody>
            {% for destinatario in cotizacion.quotereceiver_set.all %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ destinatario.nombres }}</td>
                <td>{{ destinatario.email }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>
      $(function () {
          $('.btn-send-mail').click(function (ev) {
              ev.preventDefault();

              swal({
                      title: 'Envío de la cotización',
                      text: 'Confirme el envío por correo.',
                      type: 'info',
                      showCancelButton: true,
                      closeOnConfirm: false,
                      showLoaderOnConfirm: true,
                  },
                  function () {
                      $.ajax({
                          url: '{{ cotizacion.get_send_url }}'
                      })
                          .done(function (data) {
                              swal(data.mensaje, data.str_status);
                          });
                  })
          });
      })
  </script>
{% endblock %}

quoman/templates/quotes/list.html
{% extends 'common/_base.html' %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li class='active'><a>Cotizaciones</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-xs-12'>
      <div class='box'>
        <div class='box-header'>
          <h1 class='box-title'>Cotizaciones</h1>

          <div class='box-tools'>
            <a href='{% url "quotes:new" %}' class='btn btn-block btn-primary'>
              <i class="fa fa-plus" aria-hidden="true"></i>
              Crear Cotización
            </a>
          </div>
        </div>

        <div class='box-body table-responsive no-padding'>

          <table class='table table-bordered table-responsive table-striped table-hover'>
            <thead>
            <tr>
              <th>#</th>
              <th>Código</th>
              <th>Propietario</th>
              <th>Estado</th>
              <th>RUC</th>
              <th>Válida hasta</th>
              <th>Total</th>
              <th>Ver</th>
            </tr>
            </thead>

            <tbody>
            {% for cotizacion in lista_cotizaciones %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href='{{ cotizacion.get_absolute_url }}'>{{ cotizacion.codigo|upper }}</a></td>
                <td>{{ cotizacion.propietario_id.userprofile.full_name }}</td>
                <td>{{ cotizacion.get_estado_display }}</td>
                <td>{{ cotizacion.ruc }}</td>
                <td>{% if cotizacion.valida_hasta %}{{ cotizacion.valida_hasta|date:'d M Y' }} {% else %}
                  - {% endif %}</td>
                <td>{{ cotizacion.total }}</td>
                <td><a href='{{ cotizacion.get_detail_url }}'>Detalle</a></td>
              </tr>
            {% empty %}
              <tr>
                <td colspan='6'>No hay cotizaciones registradas</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

quoman/templates/quotes/new_edit.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li><a href='{% url 'quotes:list' %}'>Cotizaciones</a></li>
            <li class='active'><a>{% if cotizacion %}{{ cotizacion.codigo }}{% else %}Nueva Cotización{% endif %}</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-header with-border">
      <h1 class='box-title'>Cotización {% if producto %}Edición{% else %}Registro{% endif %}</h1>

      {% if form.instance.codigo %}
        <div class='box-tools'>
          <a href='{{ cotizacion.get_pdf_url }}' class='btn btn-block' target='_blank'>
            <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
            Vista previa en PDF
          </a>
        </div>
      {% endif %}
    </div>

    <form class='form-horizontal form-condensed' action='#' method='POST' enctype='multipart/form-data'>
      <div class="box-body">
        {% csrf_token %}
        {{ quoteReceiverFormSet.management_form }}
        {{ quoteProductFormSet.management_form }}

        {% crispy form form.helper %}

        <fieldset>
          <legend>Productos</legend>
          <div id='formset-productos'>
            {% for form in quoteProductFormSet %}
              <div class='product_inline inline-item'>
                {% crispy form form.helper %}
              </div>
            {% endfor %}
          </div>

          <div class='row'>
            <div class="col-lg-2 text-right">
              <button id='btnProducto' class='btn'>
                <i class="fa fa-plus" aria-hidden="true"></i>
                Añadir Producto
              </button>
            </div>
          </div>
        </fieldset>

        <fieldset>
          <legend>Destinatarios</legend>
          <ul id='formset-destinatarios'>
            {% for form in quoteReceiverFormSet %}
              {% crispy form helper %}
            {% endfor %}
          </ul>

          <div class="col-lg-2 text-right">
            <button id='btnDestinatario' class='btn'>
              <i class="fa fa-plus" aria-hidden="true"></i>
              Añadir Destinatario
            </button>
          </div>
        </fieldset>
      </div>

      <div class="box-footer">
        <div class="row">
          <div class="col-lg-2 text-right">
            <button class='btn btn-primary'>
              <i class="fa fa-floppy-o" aria-hidden="true"></i>
              Enviar
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}


{% block js %}
  <script type='template/productos'>
    <div class='product_inline'>
      {% crispy quoteProductFormSet.empty_form helper %}
    </div>
  </script>

  <script type='template/destinatarios'>
    {% crispy quoteReceiverFormSet.empty_form helper %}
  </script>

  <script>
      $(function () {
          // cotizaciones
          var $totalDestinatarios = $('#id_quotereceiver_set-TOTAL_FORMS');

          $('#btnDestinatario').click(function (event) {
              event.preventDefault();
              var total = parseInt($totalDestinatarios.val(), 10);
              var clon = $('script[type="template/destinatarios"]').html();
              clon_html = replaceAll(clon, '__prefix__', (total).toString());
              $('#formset-destinatarios').append(clon_html);
              $totalDestinatarios.val(total + 1);
          });

          // productos
          var $totalProductos = $('#id_productos_a_cotizar-TOTAL_FORMS');

          $('#btnProducto').click(function (event) {
              event.preventDefault();
              var total = parseInt($totalProductos.val(), 10);
              var clon = $('script[type="template/productos"]').html();
              clon_html = replaceAll(clon, '__prefix__', (total).toString());
              $('#formset-productos').append(clon_html);
              $totalProductos.val(total + 1);
          });

          // cambio de un producto
          $('body').on('change', '.product_inline .producto', function (ev) {
              ev.preventDefault();
              var _this = $(this),
                  _id = _this.val(),
                  _parent = _this.closest('.product_inline');

              if (!_id) {
                  return;
              }

              $.ajax({
                  url: '/productos/api/' + _id + '/?format=json',
              })
                  .done(function (data) {
                      _parent.find('.sku').val(data.sku);
                      _parent.find('.nombre').val(data.nombre);
                      _parent.find('.detalle').val(data.detalle);
                      _parent.find('.precio').val(data.precio);
                  });
          })
      })
  </script>
{% endblock js %}