quoman/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('quoman.urls', namespace='quoman')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^cotizaciones/', include('quotes.urls', namespace='quotes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quoman/quoman/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
]

quoman/quotes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^lista/$', views.quotes_list, name='list'),
    url(r'^nuevo/$', views.quotes_new, name='new'),
    url(r'^editar/(?P<codigo>[-_\w]+)/$', views.quotes_edit, name='edit'),
    url(r'^detalle/(?P<codigo>[-_\w]+)/$', views.quotes_detail, name='detail'),
    url(r'^pdf/(?P<codigo>[-_\w]+)/$', views.quotes_pdf, name='pdf'),
    url(r'^enviar/(?P<codigo>[-_\w]+)/$', views.send_quote, name='send_quote'),
]

quoman/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login'),
    url(r'^salir/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.profile, name='profile'),
    url(r'^perfil/password/$', views.update_password, name='update_password'),
    url(r'^olvido-password/$', views.forget_password, name='forget_password'),
    url(r'^cambiar-password/(?P<profile_id>\d+)/(?P<uuid>[^/]+)/$', views.set_password, name='set_password'),
]

quoman/templates/common/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>QuoMan</title>

  <link rel='stylesheet' href='{% static "bootstrap/css/bootstrap.min.css" %}'>
  <link rel='stylesheet' href='{% static "adminlte/css/AdminLTE.min.css" %}'>
  <link rel='stylesheet' href='{% static "adminlte/css/skin-blue-light.min.css" %}'>
  <link rel='stylesheet' href='{% static "font-awesome/css/font-awesome.min.css" %}'>
  <link rel='stylesheet' href='{% static "plugins/datepicker/datepicker3.css" %}'>
  <link rel="stylesheet" href='{% static "plugins/sweetalert/sweetalert.css" %}'>

  <link rel='stylesheet' href='{% static "css/main.css" %}'>
</head>

<body class='skin-blue-light fixed'>

<div class="wrapper">
  {% include 'common/_header.html' %}

  <div class='content-wrapper'>
    <div class='content body'>
      {% include 'common/_messages.html' %}

      {% block content %}
      {% endblock content %}
    </div>
  </div>

</div>

<script src='{% static "js/jquery-2.2.4.min.js" %}'></script>
<script src='{% static "bootstrap/js/bootstrap.min.js" %}'></script>
<script src='{% static "adminlte/js/app.min.js" %}'></script>

<script src='{% static "plugins/slimScroll/jquery.slimscroll.min.js" %}'></script>
<script src='{% static "plugins/datepicker/bootstrap-datepicker.js" %}'></script>
<script src='{% static "plugins/datepicker/locales/bootstrap-datepicker.es.js" %}'></script>
<script src='{% static "plugins/sweetalert/sweetalert.min.js" %}'></script>
<script src='{% static "js/utils.js" %}'></script>

{% block js %}
{% endblock js %}
</body>
</html>

quoman/templates/common/_header.html
{% if request.user.is_authenticated %}
  <header class="main-header">
    <a href='#' class='logo'>Logo</a>

    <nav class='navbar navbar-static-top'>
      <a href='#' class='sidebar-toggle' data-toggle='offcanvas' role='button'>
        <span class="sr-only">Mostrar/Ocultar menú</span>
      </a>

      <div class='navbar-custom-menu'>
        <ul class='nav navbar-nav'>
          <li>
            <a href='{% url "users:profile" %}' class='bold'>
              <i class='fa fa-user-circle-o' aria-hidden='true'></i>

              {% if request.use.full_name %}
                {{ request.use.full_name }}
              {% else %}
                {{ request.user }}
              {% endif %}</a>
          </li>

          <li>
            <a href='{% url "users:logout" %}'>
              <i class='fa fa-sign-out' aria-hidden='true'></i>
              Salir
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <aside class='main-sidebar'>
    <div class='sidebar'>

      <ul class='nav sidebar-menu'>
        <li><a href='{% url "quoman:dashboard" %}'><i class="fa fa-home" aria-hidden="true"></i>Dashboard</a></li>
        <li><a href='{% url "products:list" %}'><i class="fa fa-wrench" aria-hidden="true"></i>
          Productos</a></li>
        <li><a href='{% url "quotes:list" %}'><i class="fa fa-table" aria-hidden="true"></i>Cotizaciones</a></li>

        <li>
          <a href='{% url "users:logout" %}'>
            <i class='fa fa-sign-out' aria-hidden='true'></i>
            Salir
          </a>
        </li>
      </ul>

    </div>
  </aside>
{% endif %}

quoman/templates/common/_messages.html
{% if messages %}
  {% for message in messages %}
    <div class='alert {% if message.tags %} alert-{{ message.tags }}{% endif %}'>{{ message }}</div>
  {% endfor %}
{% endif %}