quoman/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('quoman.urls', namespace='quoman')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^cotizaciones/', include('quotes.urls', namespace='quotes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quoman/quoman/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
]

quoman/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login'),
    url(r'^salir/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.profile, name='profile'),
    url(r'^perfil/password/$', views.update_password, name='update_password'),
    url(r'^olvido-password/$', views.forget_password, name='forget_password'),
    url(r'^cambiar-password/(?P<profile_id>\d+)/(?P<uuid>[^/]+)/$', views.set_password, name='set_password'),
]

quoman/users/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models

from . import constants


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField('Rol', max_length=32, choices=constants.ROLES, default=constants.ROL_VENDEDOR)
    email = models.EmailField('Email', max_length=64)
    nombres = models.CharField('Nombres', max_length=64)
    apellidos = models.CharField('Apellidos', max_length=64)
    telefono = models.CharField('Teléfono', max_length=32, blank=True)
    uuid = models.UUIDField('UUID', default=uuid.uuid4, editable=False)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __str__(self):
        return self.full_name()

    def full_name(self):
        return '{} {}'.format(self.nombres, self.apellidos)

quoman/users/forms.py
import uuid

from django import forms
from django.contrib.auth import authenticate
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.conf import settings

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.EmailField(label='Email')
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            UserProfile.objects.get(email=username)
        except UserProfile.DoesNotExist:
            mensaje = 'El email no ha sido registrado'
            raise forms.ValidationError(mensaje)

        return username

    def auth(self):
        cleaned_data = self.cleaned_data
        return authenticate(username=cleaned_data['username'], password=cleaned_data['password'])


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('email', 'nombres', 'apellidos', 'telefono')


class PasswordUpdateForm(forms.Form):
    old_password = forms.CharField(label='Antigua Contraseña', widget=forms.PasswordInput)
    new_password = forms.CharField(label='Nueva Contraseña', widget=forms.PasswordInput, min_length=6)

    def update_password(self, user):
        new_password = self.cleaned_data.get('new_password')
        user.set_password(new_password)
        user.save()


class RecoverPasswordForm(forms.Form):
    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            self.u = UserProfile.objects.get(email=email)
        except UserProfile.DoesNotExist:
            mensaje = 'El email no ha sido registrado'
            raise forms.ValidationError(mensaje)

        return email

    def send_mail(self):
        htmly = get_template('users/email_request_password.html')
        cd = self.cleaned_data
        cd['user'] = self.u
        cd['SITE'] = settings.SITE_URL
        d = Context(cd)

        html_content = htmly.render(d)
        asunto = 'Actualización de Contraseña'
        mail = '{0}<{1}>'.format(settings.PROJECT_NAME, settings.DEFAULT_FROM_EMAIL)
        destinatarios = [self.u.email]
        msg = EmailMessage(asunto, html_content, mail, destinatarios)
        msg.content_subtype = "html"
        msg.send()


class SetPasswordForm(forms.Form):
    uuid = forms.CharField(widget=forms.HiddenInput)
    email = forms.EmailField(label='Email')
    email.widget.attrs.update({'readonly': 'readonly'})
    password = forms.CharField(label='Nueva contraseña', min_length=6,
                               max_length=32, widget=forms.PasswordInput)

    def clean_email(self):
        uuid = self.cleaned_data['uuid']
        email = self.cleaned_data['email']
        try:
            self.u = UserProfile.objects.get(email=email, uuid=uuid)
        except UserProfile.DoesNotExist:
            raise forms.ValidationError('El email o la clave temporal son incorrectos!')

        return email

    def save(self):
        cd = self.cleaned_data
        usuario = self.u
        usuario.user.set_password(cd['password'])
        usuario.uuid = uuid.uuid4()
        usuario.save()
        usuario.user.save()

    def send_mail(self):
        htmly = get_template('users/email_recover_password.html')
        site = settings.SITE_URL
        cd = self.cleaned_data
        cd['SITE'] = settings.SITE_URL
        cd['user'] = self.u
        d = Context(cd)

        html_content = htmly.render(d)
        asunto = u'Actualización de Contraseña'
        mail = '{0}<{1}>'.format(settings.PROJECT_NAME,
                                 settings.DEFAULT_FROM_EMAIL)
        msg = EmailMessage(asunto, html_content, mail, [self.u.email])
        msg.content_subtype = "html"
        msg.send()

quoman/users/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect

from .forms import LoginForm
from .forms import UserProfileForm
from .forms import PasswordUpdateForm
from .forms import RecoverPasswordForm
from .forms import SetPasswordForm
from users.models import UserProfile
from quoman.helpers import DefaultFormHelper
from quoman.helpers import BaseFormHelper


def login_view(request):
    if request.user.is_authenticated():
        return redirect(reverse('quoman:dashboard'))

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = form.auth()

            if user is not None:
                if user.is_active:
                    login(request, user)

                    location = request.GET.get('next', None)

                    if location:
                        return redirect(location)

                    return redirect(reverse('quoman:dashboard'))
                else:
                    messages.add_message(request, messages.WARNING,
                                         'El usuario no se encuentra activo')
            else:
                messages.add_message(request, messages.WARNING,
                                     'El email y contraseña son inválidos')
        else:
            messages.add_message(request, messages.WARNING, 'Error de formulario')
    else:
        form = LoginForm()

    helper = BaseFormHelper

    return render(request, 'users/login.html', locals())


def logout_view(request):
    return logout_then_login(request)


@login_required
def profile(request):
    user_profile = request.user.userprofile

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)

        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Perfil actualizado')
    else:
        form = UserProfileForm(instance=user_profile)

    helper = DefaultFormHelper

    return render(request, 'users/profile.html', locals())


@login_required
def update_password(request):
    user = request.user

    if request.method == 'POST':
        form = PasswordUpdateForm(request.POST)

        if form.is_valid():
            old_password = form.cleaned_data.get('old_password')
            if user.check_password(old_password):
                form.update_password(user)
                messages.add_message(request, messages.SUCCESS, 'Contraseña actualizada')
            else:
                messages.add_message(request, messages.ERROR, 'La contraseña actual no coincide')
    else:
        form = PasswordUpdateForm()

    helper = DefaultFormHelper

    return render(request, 'users/password_update.html', locals())


def forget_password(request):
    """ Pantalla para recuperar la contraseña """

    if request.method == 'POST':
        form = RecoverPasswordForm(request.POST)

        if form.is_valid():
            form.send_mail()
            messages.add_message(request, messages.SUCCESS, 'Se le enviaron las intrucciones por correo')
            return redirect('users:login')
    else:
        form = RecoverPasswordForm()

    helper = BaseFormHelper

    return render(request, 'users/recover_password.html', locals())


def set_password(request, profile_id, uuid):

    if request.method == 'POST':
        form = SetPasswordForm(request.POST)
        if form.is_valid():
            form.save()
            form.send_mail()
            messages.add_message(request, messages.SUCCESS, 'Contraseña actualizada correctamente')
            return redirect(reverse('users:login'))
    else:
        try:
            user = UserProfile.objects.get(uuid=uuid, id=profile_id)
        except UserProfile.DoesNotExist:
            user = None
        form = SetPasswordForm(initial={'email': user.email, 'uuid': uuid})

    helper = BaseFormHelper

    return render(request, 'users/set_password.html', locals())

quoman/templates/users/email_recover_password.html
{% load static %}
{% spaceless %}

  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
      "http://www.w3.org/TR/html4/loose.dtd">

  <html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Recuperación de Contraseña</title>

    <style>
      a:hover {
        text-decoration: underline !important;
      }

      td.contentblock h4 {
        color: #444444 !important;
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        margin-top: 0;
        margin-bottom: 10px;
        padding-top: 0;
        padding-bottom: 0;
        font-weight: normal;
      }

      td.contentblock h4 a {
        color: #444444;
        text-decoration: none;
      }

      td.contentblock p {
        color: #888888;
        font-size: 13px;
        line-height: 19px;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        margin-top: 0;
        margin-bottom: 12px;
        padding-top: 0;
        padding-bottom: 0;
        font-weight: normal;
      }

      td.contentblock p a {
        color: #3ca7dd;
        text-decoration: none;
      }

      @media only screen and (max-device-width: 480px) {
        table[class="table"], td[class="cell"] {
          width: 300px !important;
        }

        table[class="hide"], img[class="hide"], td[class="hide"] {
          display: none !important;
        }

        img[class="divider"] {
          height: 1px !important;
        }

        td[class="logocell"] {
          padding-top: 15px !important;
          padding-left: 15px !important;
          width: 300px !important;
        }

        h4[class="secondary"] {
          line-height: 22px !important;
          margin-bottom: 15px !important;
          font-size: 18px !important;
        }
      }

    </style>
  </head>

  <body bgcolor="#e4e4e4" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0"
        style="-webkit-font-smoothing: antialiased;width:100% !important;background:#e4e4e4;-webkit-text-size-adjust:none;">

  <table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e4e4e4">
    <tr>
      <td bgcolor="#e4e4e4" width="100%">

        <table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
          <tr>
            <td width="600" class="cell">

              <table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
                <tr>
                  <td width="250" bgcolor="#e4e4e4" class="logocell">
                    <img border="0" src="{% static 'images/logo.png' %}" width="1" height="20"
                         class="hide"><br class="hide"><img src="{% static 'images/logo.png' %}"
                                                            width="178" height="76" alt="-"
                                                            style="-ms-interpolation-mode:bicubic;"><br><img border="0"
                                                                                                             src="{% static 'images/logo.png' %}"
                                                                                                             width="1"
                                                                                                             height="10"
                                                                                                             class="hide"><br
                      class="hide"></td>
                  <td align="right" width="350" class="hide"
                      style="color:#a6a6a6;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;text-shadow: 0 1px 0 #ffffff;"
                      valign="top" bgcolor="#e4e4e4"><img border="0" src="{% static 'images/logo.png' %}"
                                                          width="1" height="63"><br><span> {{ PROJECT_NAME }} </span>
                  </td>
                </tr>
              </table>

              <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td bgcolor="#85bdad" nowrap><img border="0" src="{% static 'images/logo.png' %}"
                                                    width="5" height="1"></td>

                  <td width="100%" bgcolor="#ffffff">

                    <table width="100%" cellpadding="20" cellspacing="0" border="0">
                      <tr>
                        <td bgcolor="#ffffff" class="contentblock">

                          <h4 class="secondary">
                            <strong><p label="Title">Recuperación de Contraseña</p></strong>
                          </h4>
                          <p label="Description">
                          <p>Su contraseña fue actualizada.</p>

                        </td>
                      </tr>
                    </table>

                  </td>
                </tr>
              </table>
              <img border="0" src="{% static 'images/logo.png' %}" width="1" height="15"
                   class="divider"><br>

            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

  </body>
  </html>
{% endspaceless %}

quoman/templates/users/email_request_password.html
{% load static %}

{% spaceless %}

  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
      "http://www.w3.org/TR/html4/loose.dtd">

  <html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>RECUPERACIÓN DE CONTRASEÑA</title>

    <style>
      a:hover {
        text-decoration: underline !important;
      }

      td.contentblock h4 {
        color: #444444 !important;
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        margin-top: 0;
        margin-bottom: 10px;
        padding-top: 0;
        padding-bottom: 0;
        font-weight: normal;
      }

      td.contentblock h4 a {
        color: #444444;
        text-decoration: none;
      }

      td.contentblock p {
        color: #888888;
        font-size: 13px;
        line-height: 19px;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        margin-top: 0;
        margin-bottom: 12px;
        padding-top: 0;
        padding-bottom: 0;
        font-weight: normal;
      }

      td.contentblock p a {
        color: #3ca7dd;
        text-decoration: none;
      }

      @media only screen and (max-device-width: 480px) {

        table[class="table"], td[class="cell"] {
          width: 300px !important;
        }

        table[class="hide"], img[class="hide"], td[class="hide"] {
          display: none !important;
        }

        img[class="divider"] {
          height: 1px !important;
        }

        td[class="logocell"] {
          padding-top: 15px !important;
          padding-left: 15px !important;
          width: 300px !important;
        }

        h4[class="secondary"] {
          line-height: 22px !important;
          margin-bottom: 15px !important;
          font-size: 18px !important;
        }
      }

    </style>
  </head>

  <body bgcolor="#e4e4e4" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0"
        style="-webkit-font-smoothing: antialiased;width:100% !important;background:#e4e4e4;-webkit-text-size-adjust:none;">

  <table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e4e4e4">
    <tr>
      <td bgcolor="#e4e4e4" width="100%">

        <table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
          <tr>
            <td width="600" class="cell">

              <table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
                <tr>
                  <td width="250" bgcolor="#e4e4e4" class="logocell">
                    <img border="0" src="{% static 'images/spacer.gif' %} }}" width="1" height="20" class="hide"><br
                      class="hide"><img src="{% static 'images/logo.png' %}" width="178" height="76"
                                        alt="-" style="-ms-interpolation-mode:bicubic;"><br><img border="0"
                                                                                                 src="{% static 'images/logo.png' %}"
                                                                                                 width="1" height="10"
                                                                                                 class="hide"><br
                      class="hide"></td>
                  <td align="right" width="350" class="hide"
                      style="color:#a6a6a6;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;text-shadow: 0 1px 0 #ffffff;"
                      valign="top" bgcolor="#e4e4e4"><img border="0" src="{% static 'images/logo.png' %}"
                                                          width="1" height="63"><br><span>PROJECT NAME</span>
                  </td>
                </tr>
              </table>

              <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td bgcolor="#85bdad" nowrap><img border="0" src="{% static 'images/logo.png' %}"
                                                    width="5" height="1"></td>

                  <td width="100%" bgcolor="#ffffff">

                    <table width="100%" cellpadding="20" cellspacing="0" border="0">
                      <tr>
                        <td bgcolor="#ffffff" class="contentblock">

                          <h4 class="secondary">
                            <strong>
                              Recuperación de Contraseña
                            </strong>
                          </h4>
                          <p label="Description">
                          <p>Puede actualizar su contraseña desde el siguiente
                            vínculo:</p>

                          <table cellspacing="10" style="width:100%;">
                            <tr>
                              <td style='width: 20%;'>
                                <strong>Actualice su contraseña mediante el siguiente enlace: </strong>
                              </td>
                              <td><a href="{{ SITE }}{% url 'users:set_password' profile_id=user.id uuid=user.uuid %}">{{ SITE }}{% url 'users:set_password' profile_id=user.id uuid=user.uuid %}</a></td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>

                  </td>
                </tr>
              </table>
              <img border="0" src="{% static 'images/logo.png' %}" width="1" height="15"
                   class="divider"><br>

            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

  </body>
  </html>
{% endspaceless %}

quoman/templates/users/login.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="login-box">
    <div class="login-logo">
      <a href="#"><b>Admin</b>LTE</a>
    </div>

    <div class="login-box-body">
      <p class="login-box-msg">Ingrese sus credenciales</p>

      <form action='#' method='POST'>
        {% crispy form helper %}

        <div class="row">
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Acceder</button>
          </div>
        </div>
      </form>

      <br>
      <a href='{% url "users:forget_password" %}'>¿Ha olvidado su contraseña?</a>

    </div>
  </div>

{% endblock content %}

quoman/templates/users/password_update.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li><a href='{% url "users:profile" %}'>Mi Perfil</a></li>
            <li class='active'>Actualizar contraseña</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-header with-border">
      <h1 class='box-title'>Actualizar contraseña</h1>
    </div>

    <form class='form-horizontal' action='#' method='POST'>
      <div class="box-body">
        {% crispy form helper %}
      </div>

      <div class="box-footer">
        <div class="row">
          <div class="col-lg-2 text-right">
            <button class='btn btn-primary'>
              Enviar
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

quoman/templates/users/profile.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li class='active'><a>Mi Perfil</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-header with-border">
      <h1 class='box-title'>Mi Perfil</h1>
    </div>

    <form class='form-horizontal' action='#' method='POST' enctype='multipart/form-data'>
      <div class="box-body">
        {% crispy form helper %}
      </div>

      <div class="box-footer">
        <div class="row">
          <div class="col-lg-2 text-right">
            <button class='btn btn-primary'>
              <i class="fa fa-floppy-o" aria-hidden="true"></i>
              Enviar
            </button>
          </div>
        </div>
      </div>
    </form>

    <div class='row'>
      <div class='col-lg-2 text-right'>
        <a href='{% url "users:update_password" %}' class='bold'>Cambiar contraseña</a>
      </div>
    </div>
  </div>
{% endblock content %}

quoman/templates/users/recover_password.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="login-box">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h1 class='box-title'>Recuperar contraseña</h1>
      </div>

      <form action='#' method='POST'>
        <div class="box-body">
          {% crispy form helper %}
        </div>

        <div class="box-footer">
          <button class='btn btn-primary'>Enviar</button>
        </div>

        <div class="box-footer">
          <a href='{% url "users:login" %}'>Si recuerdo mi contraseña</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

quoman/templates/users/set_password.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="login-box">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h1 class='box-title'>Cambio de contraseña</h1>
      </div>

      <form class='form-horizontal' action='#' method='POST'>
        <div class="box-body">
          {% crispy form helper %}
        </div>

        <div class="box-footer">
          <button class='btn btn-primary'>Enviar</button>
        </div>

        <div class="box-footer">
          <a href='{% url "users:login" %}'>Si recuerdo mi contraseña</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}