quoman/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('quoman.urls', namespace='quoman')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^cotizaciones/', include('quotes.urls', namespace='quotes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quoman/products/urls.py
from django.conf.urls import url

from . import views
from . import api


urlpatterns = [
    url(r'^lista/$', views.products_list, name='list'),
    url(r'^nuevo/$', views.products_new, name='new'),
    url(r'^editar/(?P<sku>[-\w]+)/$', views.products_edit, name='edit'),

    # api
    url(r'^api/(?P<pk>[0-9]+)/$', api.ProductDetail.as_view(), name='api_detail'),
]

quoman/quoman/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
]

quoman/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login'),
    url(r'^salir/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.profile, name='profile'),
    url(r'^perfil/password/$', views.update_password, name='update_password'),
    url(r'^olvido-password/$', views.forget_password, name='forget_password'),
    url(r'^cambiar-password/(?P<profile_id>\d+)/(?P<uuid>[^/]+)/$', views.set_password, name='set_password'),
]

quoman/products/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Product(models.Model):
    sku = models.CharField('SKU', max_length=32, unique=True, db_index=True,
                           help_text='Identificador único')
    nombre = models.CharField('Nombre', max_length=64, db_index=True)
    detalle = models.TextField('Detalle', blank=True)
    precio = models.DecimalField('Precio', max_digits=12, decimal_places=2,
                                 help_text='Precio en soles con dos decimales como máximo.')
    imagen = models.ImageField('Imagen', upload_to='productos', blank=True, null=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['sku']

    def __str__(self):
        return self.sku

    def get_absolute_url(self):
        return reverse('products:edit', kwargs={'sku': self.sku})

    def get_api_detail_url(self):
        return reverse('products:api_detail', kwargs={'id': self.id})

quoman/products/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Product


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.form_tag = False

        self.helper.add_input(Submit('submit', 'Enviar'))

    class Meta:
        model = Product
        fields = ('sku', 'nombre', 'detalle', 'imagen', 'precio')

quoman/products/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from .models import Product
from .forms import ProductForm
from quoman.helpers import DefaultFormHelper


@login_required
def products_list(request):
    lista_productos = Product.objects.order_by('sku')

    return render(request, 'products/list.html', locals())


@login_required
def products_new(request):

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            producto = form.save()
            messages.add_message(request, messages.SUCCESS, 'Se registró el producto')

            return redirect(producto.get_absolute_url())
    else:
        form = ProductForm()

    helper = DefaultFormHelper

    return render(request, 'products/new_edit.html', locals())


@login_required
def products_edit(request, sku):
    # TODO: retornar a la lista de productos en caso se no encuentre el buscado
    producto = get_object_or_404(Product, sku=sku)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=producto)

        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Se actualizó el producto')

    else:
        form = ProductForm(instance=producto)

    helper = DefaultFormHelper
    
    return render(request, 'products/new_edit.html', locals())

quoman/templates/products/list.html
{% extends 'common/_base.html' %}

{% block content %}

  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li class='active'><a>Productos</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-xs-12'>
      <div class='box'>
        <div class='box-header'>
          <h1 class='box-title'>Productos</h1>

          <div class='box-tools'>
            <a href='{% url "products:new" %}' class='btn btn-block btn-primary'>
              <i class="fa fa-plus" aria-hidden="true"></i>
              Crear Producto
            </a>
          </div>
        </div>

        <div class='box-body table-responsive no-padding'>

          <table class='table table-bordered table-responsive table-striped table-hover'>
            <thead>
            <tr>
              <th>#</th>
              <th>SKU</th>
              <th>Nombre</th>
            </tr>
            </thead>

            <tbody>
            {% for producto in lista_productos %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href='{{ producto.get_absolute_url }}'>{{ producto.sku|upper }}</a></td>
                <td>{{ producto.nombre }}</td>
              </tr>
            {% empty %}
              <tr>
                <td colspan='3'>No hay productos registrados</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

quoman/templates/products/new_edit.html
{% extends 'common/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <ul class='breadcrumb'>
            <li><a href='{% url 'quoman:dashboard' %}'> <i class="fa fa-home" aria-hidden="true"></i> Dashboard</a></li>
            <li><a href='{% url 'products:list' %}'>Productos</a></li>
            <li class='active'><a>{% if producto %}{{ producto.nombre }}{% else %}Nuevo Producto{% endif %}</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-header with-border">
      <h1 class='box-title'>Producto {% if producto %}Edición{% else %}Registro{% endif %}</h1>
    </div>

    <form class='form-horizontal' action='#' method='POST' enctype='multipart/form-data'>
      <div class="box-body">
        {% crispy form helper %}
      </div>

      <div class="box-footer">
        <div class="row">
          <div class="col-lg-2 text-right">
            <button class='btn btn-primary'>
              <i class="fa fa-floppy-o" aria-hidden="true"></i>
              Enviar
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}